source = ~/.config/hypr/background.conf
wallpaper {
  monitor = eDP-2
  path = ~/Pictures/Backgrounds/Secondary/SEKIGUCHI_Wallpaper_Symbol_Purple.png
  fit_mode=fill
}
wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Backgrounds/Pimary/Cradle_Enviormental_large.jpg
  fit_mode = fill
}
splash=false
