source = ~/.config/hypr/background.conf
wallpaper {
  monitor = eDP-1
  path = ~/Pictures/Backgrounds/SEKIGUCHI_Wallpaper_Symbol_Purple.png
  fit_mode=fill
}
wallpaper {
  monitor = DP-1
  path = ~/Pictures/Backgrounds/SEKIGUCHI_Wallpaper_Purple.png
  fit_mode = fill
}
splash=false
