unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set-option -sa terminal-overrides ",xterm*Tc" #color thingey, apparantly

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @tokyo-night-tmux_show_datetime 1   # 1 = enabled (default) | 0 = disabled
set -g @tokyo-night-tmux_date_format DMY   # see options below
set -g @tokyo-night-tmux_time_format 24H   # see options below
set -g @tokyo-night-tmux_window_id_style roman   # window tab numbers
set -g @tokyo-night-tmux_pane_id_style hsquare     # pane number shown in status bar
set -g @tokyo-night-tmux_zoom_id_style dsquare     # pane number shown when zoomed
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_netspeed 0        # network speed
set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
set -g @tokyo-night-tmux_show_music 0           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_show_hostname 0        # machine hostname

set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'
set -g @sessionx-tree-mode 'on'

# Update these variables when attaching to a session
set-environment -g XAUTHORITY "$HOME/.Xauthority_live"
set-option -g update-environment "DISPLAY"

# start window and pane numbering from 1 instead of 0.
set -g base-index 1
setw -g pane-base-index 1
# new panes in the same dir.
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
